Blockstream/greenlight

- tools/glcli/glcli/cli.py
Pass the network set via `--network` through to the signer and the scheduler so that `register` can pick it up.
> Add `network` to the glcli `register` call

- libs/Cargo.lock
- libs/gl-client/Cargo.toml
- libs/gl-client/src/scheduler.rs
The branches in the VLS repository keep disappearing, so let's archive the state that we know works, and reference those instead.
> vls: Switch to snapshot repository

- libs/gl-client-py/pyproject.toml
The wheel name was using the Cargo name, whereas we need to have the non-suffixed version.
> py: Re-add pyproject metadata

- libs/Cargo.lock
- libs/gl-client/Cargo.toml
- libs/gl-client/src/signer/mod.rs
Apparently we dropped a backward compatibility shim while catching up with VLS `main`.
> vls: Update to VLS v0.9.1rc2

- libs/gl-plugin/src/responses.rs
We get empty `preimage` for payments retrieved via `list_payments` endpoint.
By observing the node client `list_pays` endpoint it seems that the value there is correct but renamed differently causing the deserialization result in empty string.
I don't have a way to test it currently but pretty sure this will fix it.
> Fix empty preimage

- libs/gl-client/src/signer/mod.rs
If we have a mismatch between the signer and the node, specifically with the node older than the client, we can end up in a situation where the parsing of the context fails, despite not actually being fatal, and then getting stuck until the node restarts.
This now complains about any failure to parse the context, but will still go ahead and try reconciling for the E2E verification. This works because the failure in #193 was a read-only request and not even required in the context.
This PR is part 1 of the proposed solutions in #193.
> Allow partial request context parsing

- libs/gl-client-js/Cargo.toml
- libs/gl-client-js/package.json
- libs/gl-client-py/Cargo.toml
- libs/gl-client-py/pyproject.toml
- libs/gl-client/Cargo.toml
We want to ship some of the recent changes to users:
- #195 
- #194 
- #190 
- #189 
- #182
> libs: Bump client bindings version for publication

- libs/Cargo.lock
- libs/gl-plugin/src/node/mod.rs
- libs/gl-testing/tests/test_node.py
We were having issues with nodes not reconnecting some times. We traced the issue to the signer connecting very early on, when the RPC is not available yet, causing the `connect()` calls yelling into the void.
By refactoring the reconnection logic and calling it both from the RPC watcher and the signer connecting should address that.
> Reconnect both when a signer attaches and when the RPC becomes available

- libs/gl-plugin/src/bin/plugin.rs
The signature of the constructor of a `WrappedNodeServer` has been changed by a previous commit.
> Fix plugins `start_node_server`

- libs/gl-client-py/glclient/__init__.py
- libs/gl-client-py/glclient/tls.py
- libs/gl-testing/gltesting/scheduler.py
Stop using features that have been released in python-3.7 to ensure compatibility.
This replaces [MR 217](https://github.com/Blockstream/greenlight/pull/217)
> Fix python3.7

- libs/Cargo.lock
- libs/gl-client/src/signer/mod.rs
Errors when talking to the node or the scheduler are varied, and our reaction to them needs to be as well. So let's introduce a custom error type, that we can then use to differentiate connection issues, from disconnections, and from app level errors.
In particular we want to go back to the scheduler if we lost contact while streaming, but not if there is an app level error.
> signer: Introduce an Error enum to selectively react to errors

- Makefile
- docs/src/about/changelog.md
- libs/gl-client/build.rs
- libs/gl-client/src/lib.rs
- libs/gl-client/src/node/mod.rs
- libs/gl-client/src/scheduler.rs
- libs/gl-client/src/signer/mod.rs
Allows us to passively detect that we lost a connection after 90s. While not quite usable for interactive scenarios (signer in keep alive timeout, client is waiting on signatures), it is useful for the standard case where the signer lost the connection while waiting for the node to get scheduled.
A deeper integration with the host's sleep state, restarting the signer when we come back from suspension for example, can be a complementary technique to address those interactive scenarios.
Closes #209
> client: Add keepalive to signer, scheduler and node connections

- .github/workflows/check-self.yml
- Makefile
- libs/Cargo.lock
- libs/gl-client/Cargo.toml
- libs/gl-plugin/src/lsp.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-plugin/src/node/wrapper.rs
- libs/gl-plugin/src/pb.rs
- libs/gl-testing/Dockerfile
We were seeing an incomplete enum matching due to `txoo = "0.4.2"` allowing version `0.4.5` to be pulled in, which however added an element to the enum.
Also updates `cln-rpc` and `cln-grpc` to add `list_htlcs` and `static_backup` methods.
> client: Fix `txoo` breaking semantic versioning

- libs/gl-client-py/Makefile
- libs/gl-client-py/glclient/greenlight_pb2.pyi
- libs/gl-client-py/glclient/scheduler_pb2.pyi
- libs/gl-testing/Dockerfile
- requirements-dev.txt
I added typehints using the mypy-protobuf package.
This requries that `mypy-protobuf` python package is installed.
I created a `requirements-dev.txt`-file and added it to the docker-container. The bindings can now be regenerated as follows.
Do `make docker-shell`.
Inside the newly opened shell you can enter
```
make libs/gl-client-py/Makefile pygrpc
```
and
```
make libs/gl-testing/Makefile testgrpc
```
> Typehints for python grpc-methods

- libs/gl-client/src/node/mod.rs
- libs/gl-client/src/scheduler.rs
- libs/gl-client/src/signer/mod.rs
I removed some unneeded imports which pulluted the logs with warnings
> Removed spurious import

- libs/gl-testing/Dockerfile
If you run `make clean` inside a `make docker-shell` the operation fails. It appears `jq` is missing in the docker-image
> Install jq to fix make-clean

- docs/src/getting-started/recover.md
In the python example the signer was initialised after the scheduler, but the signer.node_id() is referenced in the scheduler initialisation.
> docs: Fix python recover code example

- libs/gl-client-py/Makefile
- libs/gl-client-py/pyproject.toml
This PR adds the following two changes:
- Add `mypy-protobuf` to the `gl-client-py` dev dependencies so that we can compile the grpc files from a poetry shell.
- Improve the `Makefile` targets `clean-py` and `pygrpc` to allow them to be called from the top dir as well as from within `gl-client-py`
> Add mypy-protobuf to the dev dependencies

- libs/gl-plugin/src/node/wrapper.rs
- libs/gl-plugin/src/pb.rs
- libs/gl-plugin/src/requests.rs
- libs/gl-testing/tests/test_node.py
Due to greenlight.proto - which we need to retire at some point - we were missing some fields of the invoice rcp request message. This adds all fields that are set by cln_grpc and extends the conversion traits.
Resolves #255
> Extend the Invoice request message of the plugin wrapper

- .github/workflows/rust-unit.yml
- Makefile
- libs/gl-client/Makefile
Ensure all unit-tests are run on `CI`.
I have created a new action for this purpose. The action installs rust, protoc and runs all unit-tests defined in the `lib` folder.
I have also introduced a `make check-all` which can be used to run all tests locally.
**TODO**
The work to run the python tests is tackled in another MR
> Run unit tests in CI

- libs/gl-client/src/lsps/json_rpc_erased.rs
Note that `JsonRpcResponseErased` is an alias for `JsonRpcResponse<Vec<u8>>`
> Fix typo's in documentation and better typing

- libs/gl-client/src/persist.rs
- libs/gl-client/src/signer/mod.rs
This is to catch whatever is causing https://gitlab.com/lightning-signer/validating-lightning-signer/-/issues/397. We should be able to write a small testbench with `(signer_state, request)` tuples to reproduce the panic in an isolated environment.
> signer: Print signer state when processing requests

- libs/Cargo.lock
- libs/gl-client/Cargo.toml
We had a bit of an issue with a flag being inverted, and causing HTLC transaction fees to be misjudged, causing an unsigned integer underflow when subtracting the fees.
The relevant changes are the following:
- [channels.rs](https://gitlab.com/lightning-signer/validating-lightning-signer/-/merge_requests/537/diffs#fe030ae8388aeddd574ba9cdb46e6dda0ce107ea_2123_2123)
- [node.rs](https://gitlab.com/lightning-signer/validating-lightning-signer/-/merge_requests/537/diffs#87b90e023a5c5d97b43b1f15f00f0306da2b7966_1246_1257)
This PR just updates to the MR on the VLS gitlab, which will eventually be merged into their `main`, and we can then point to the next release.
> vls: Pull in the overflow panic fix

- libs/gl-client/src/lsps/transport.rs
I used the wrong method to write and read data from a cursors. In some cases bytes could be ignored which would result in bugs.
I've discovered this bug using clippy
> Bugfix: json_rpc transport could ignore bytes

- .github/workflows/check-self.yml
- Makefile
We were actually running python-tests instead of javascript tests.
I decided to remove the code related to run this tests to make the current behavior more explicit.
I've created https://github.com/Blockstream/greenlight/issues/272 to ensure we do not forget about this
> Remove javascript tests on CI

- libs/gl-client/src/signer/mod.rs
After removing the presplitter we may now end up with HTLCs whose fee budget exceeds the 10sat limit enforced by VLS until now. Better fee tracking on a per-payment level is needed, but this gets us going for now.
> signer: Relax fee constraints slightly

- libs/gl-client/Cargo.toml
This commit pins all unpinned dependencies of `gl-client`
This resolves #282
> Pin dependency versions

- libs/gl-plugin/src/node/wrapper.rs
This can help us avoid killing channels when the signer inadvertently goes down, by increasing the time it has to return to 1 day. We still respect the explicitly set CLTV.
Reported-by: Roei Erez <@roeierez>
> plugin: Default to 144 blocks of final CLTV delta

- libs/gl-plugin/src/node/wrapper.rs
Reconnecting can be racy, and may prolong the time until we have a
usable connection.
The problem is that reconnects force a reconnection on already
connected nodes too, which can then be racy with the `pay` itself
since `connected` will be `true` much earlier than the channel becomes
ready.
> plugin: Do not reconnect on each `pay`

- libs/Cargo.lock
- libs/gl-plugin/src/node/wrapper.rs
This adds the `wait_block_height` method
> plugin: Pull in newest cln-rpc and cln-grpc versions

- .github/workflows/python.yml
The `aarch64` configuration is broken due to the arm compiler being too old.
> gci: Fix the aarch64 python config

- libs/gl-client/src/signer/mod.rs
> signer: Increase the max_invoices limit to 10k

- libs/Cargo.lock
- libs/gl-plugin/src/node/wrapper.rs
In the lightning repository a new grpc command was added. 
This update makes it accessible in Greenlight
> Update to include datastoreusage grpc command

- .github/workflows/check-formatting.yml
- Makefile
This adds a job to the CI that checks every rust file that is changed by the PR for formatting. It will however not fail the CI (`continue-on-error: true`) and still result in a green check mark.
We could add `check-rustfmt` as a prerequisite to `check-self` if we want to run it locally and fail the CI if the formatter complains on changed files
Another option would be to use something like https://github.com/marketplace/actions/continue-on-error-comment to write a comment into the PR about formatting issues. That would not be as aggressive as to fail the CI or to enforce local checks.
Tell me what you think about this!
> Add rustfmt warning to CI

- libs/gl-client/src/signer/auth.rs
- libs/gl-client/src/signer/mod.rs
- libs/gl-testing/Dockerfile
- libs/gl-testing/tests/test_node.py
This is necessary for `sendpay` to work correctly, i.e., have the signer accept a change in balance that results from a `sendpay`, and not complain about the unexplained balance change.
Notice that this adds invoices with whicht the `sendpay` is annotated with, but does not yet register a spontaneous payment if no invoice is attached.
Reported-by: @roeierez
> signer: Extract invoices from `sendpay` command and add them to the known invoices

- Cargo.lock
- libs/gl-client/Cargo.toml
- libs/gl-client/src/lsps/error.rs
- libs/gl-client/src/lsps/json_rpc.rs
- libs/gl-client/src/lsps/json_rpc_erased.rs
- libs/gl-client/src/lsps/lsps0/common_schemas.rs
- libs/gl-client/src/lsps/lsps0/mod.rs
- libs/gl-client/src/lsps/lsps0/schema.rs
- libs/gl-client/src/lsps/lsps1/mod.rs
- libs/gl-client/src/lsps/lsps1/schema.rs
- libs/gl-client/src/lsps/lsps2/mod.rs
- libs/gl-client/src/lsps/lsps2/schema.rs
- libs/gl-client/src/lsps/message.rs
- libs/gl-client/src/lsps/mod.rs
I have implemented the data-types that are required for LSPS2.
> Implement JSON-rpc structs for LSPS2

- .gitattributes
This should make diffs much simpler, and merging will treat these as atomic changes
> git: Mark generated pb2 files as generated

- libs/gl-client/src/signer/resolve.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-signerproxy/src/hsmproxy.rs
The heartbeat serves two purposes: 1) start sending the entire state to the signer, so it can cache it locally, and 2) trigger a pruning round on the signer state.
> plugin: Send a heartbeat as first message

- libs/gl-client/src/signer/model/cln.rs
- libs/gl-client/src/signer/model/mod.rs
When calling the `FetchInvoice` command, incoming requests passing through the signer currently seem to fail with the error `Unknown URI {}, can't decode payload`, due to not being exposed in the signer. This small PR aims to fix this
> rs: allow `FetchInvoice` requests to the signer

- tools/glcli/glcli/cli.py
Hello commiters. 
Currently I develop an apps about lightning network. 
I faced a problem like this.
```shell
$ glcli getinfo
[2023-12-14 14:13:01,134 - INFO] Configuring client with user identity.
Traceback (most recent call last):
File "/usr/local/var/pyenv/versions/3.11.3/bin/glcli", line 8, in <module>
sys.exit(cli())
^^^^^
File "/usr/local/var/pyenv/versions/3.11.3/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/var/pyenv/versions/3.11.3/lib/python3.11/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/var/pyenv/versions/3.11.3/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
return …
```
> Fix getinfo command in pyhton

- libs/gl-client/src/signer/model/cln.rs
- libs/gl-client/src/signer/model/mod.rs
- libs/gl-client/src/signer/resolve.rs
Manually sending `preapproveinvoice` was failing to adjust
the context on the signer, which then declined any subsequent HTLC
matching the invoice.
Reported-By: Domenico Gabriele
> signer: Add preapproveinvoice for client-driven payments

- Cargo.lock
- Cargo.toml
- libs/gl-client/src/persist.rs
- libs/gl-client/src/signer/resolve.rs
This is in preparation for the CLN v23.11 deployment, and addition of
splice support. Splicing operations may not yet be exposed via grpc,
but we need the signer to support them first anyway.
One question for @devrandom is whether the newly introduced `SignerId`
is safe to set to a constant in our use-case, since signers are
intended to be clones of each other.
> Upgrade VLS to v0.11.0rc1

- Cargo.lock
- libs/gl-client/Cargo.toml
This PR replaces the explicit `bitcoin` dependency with the `lightning_signer::bitcoin` re-exported one, for two reasons:
First, the explicit one it's not used. The re-exported `lightning_signer::bitcoin` is already used as such, for example
https://github.com/Blockstream/greenlight/blob/62ade9c53b68b8f7625725033121babb51720dbb/libs/gl-client/src/export.rs#L5-L8
Second, the explicit dependency brings with it a separate version into the dependency tree. Removing it and instead re-using the exported one consolidates the dependency tree and helps remove duplicates.
For example, before this PR, GL had 3 separate `bitcoin` versions in the dependency tree.
```bash
cargo tree --duplicate | grep bitcoin
...
bitcoin v0.29.2 (*)
bitcoin v0.30.2 (*)
bitcoin v0.31.0 (*)
```
With this PR, there are …
> Remove duplicate bitcoin dependency

- libs/gl-client/src/lib.rs
- libs/gl-client/src/signer/approver.rs
This PR re-uses and re-exports the `lightning_signer::lightning` dependency.
This helps users of `gl-client` directly use it and avoid confusion around versioning.
> Re-export the lightning crate

- .github/workflows/python.yml
Python i686 failed on `nightly` (missing libatomic.so)
We may use `nightly` again once this is resolved.
> CI: Set stable toolchain

- libs/gl-client-py/src/lib.rs
The `SignerHandle` isn't exposed in the native-bindings. However, the `glclient.pyi` file explicitly mentions the handle should be their.
> Expose `SignerHandle` in gl-client-py

- Cargo.lock
- Cargo.toml
- signer: Upgrade to VLS v0.11.0-rc2
- client: Bump version number to 0.11 to reflect the VLS version
- signer: Upgrade to VLS 0.11.0
> signer: Upgrade to VLS 0.11.0

- .github/workflows/docs-action.yml
`permission:` -> `permissions:`
> gci: Fix typo in the docs workflow file

- libs/gl-testing/gltesting/identity.py
`set_npn_protocols` has been removed in python 3.11. 
We are already using `set_alpn_protocols` so I think we can drop it safely.
This should help us to run `gl-testing` in standalone mode
> Drop support for npn_protocols

- .dockerignore
- .github/workflows/check-self.yml
- Makefile
- docker/gl-testing/Dockerfile
- libs/gl-client-py/pyproject.toml
- pyproject.toml
This commit improves the dev-container
- faster build-time
- improved readability
> Refactor Dockerfile

- libs/gl-testing/gltesting/fixtures.py
Makes debugging easier
1. Data from fixtures using `pyln` and `gl-testing` will appear in
single folder
2. All directories stay intact after failing test
> Use directory fixture from `pyln`

- libs/gl-client/src/lib.rs
Turns out the load-balancer we are using has a very short keepalive timeout, and our old value of 30 seconds was long enough for it to drop the connection. Setting this to 5 seconds on the client, and keeping 30 seconds for the signer until we have the signer notifications working again.
> client: Adjust the keepalive interval for the load balancer

- libs/gl-testing/gltesting/node.py
The docker-image was failing to execute the tests on my machine.
A greenlight node connects to a `bitcoind`-proxy which should be exposed on `localhost`. For some reason, the proxy isn't always accepting connections when `localhost` is used.
This works
```
bitcoin-cli --rpcconnect=127.0.0.1:<proxy_port>
```
This doesn't work
```
bitcoin-cli --rpcoconnect=localhost:<proxy_port>
```
I'm not sure if this is the right approach.
We know our `bitcoind` proxy only supports `ipv4`. So I don't see a good reason to go for the more universal `localhost`?
> lightningd fails to resolve localhost

- Makefile
To reproduce the issue do `make docker-image`, `make docker-shell`,
`cargo clean`.
The issue is that you lack the rights to delete `tmp/gltesting/target`.
The folder was added as a volume and cannot be deleted.
We keep the rust target directory in `/tmp/gltesting/target/target`
instead so it can be safely deleted.
I'd recommend to run `rm -rf /tmp/gltesting` on the host-machine after merging this update.
> Fix Cargo Clean

- .github/workflows/cln-version-manager-py.yml
- docker/gl-testing/Dockerfile
- libs/cln-version-manager/.dockerignore
- libs/cln-version-manager/README.md
- libs/cln-version-manager/clnvm/__init__.py
- libs/cln-version-manager/clnvm/__main__.py
- libs/cln-version-manager/clnvm/cli.py
- libs/cln-version-manager/clnvm/cln_version_manager.py
- libs/cln-version-manager/clnvm/errors.py
- libs/cln-version-manager/clnvm/utils.py
- libs/cln-version-manager/mypy.ini
- libs/cln-version-manager/pyproject.toml
- libs/cln-version-manager/tests/test_version_manager.py
- libs/gl-testing/gltesting/node.py
- libs/gl-testing/gltesting/scheduler.py
- libs/gl-testing/gltesting/utils.py
- libs/gl-testing/pyproject.toml
- pyproject.toml
I've introduced `cln_version_manager`.
It is currently very hard to run `gl-testing` in standalone-mode.
One of the dependencies of `gl-testing` are a wide range of Core Lightning versions.
These files are packaged into the docker-file.
I've adapted the `gl-testing` python-module to download the Core Lightning binaries for the user.
It will download them to `XDG_CACHE_DIR` by default but users can configure their folder.
> Cln version manager

- libs/gl-client/src/signer/mod.rs
This PR is ported from https://github.com/breez/breez-sdk/pull/936
The original PR fixes an issue where `signer.run_once` can block for up to 10 minutes. This means that, if the signer was recently used, the signer loop would block on this call and disregard the shutdown signal for up to 10 minutes. The fix was to place the entire (inner) signer loop in a `tokio::select`, next to the shutdown signal handling.
The first part of the signer loop (scheduler initialization and `maybe_upgrade`) was extracted to a separate method as well. This part is not affected by the shutdown signal.
Note: in our version of the loop, we use `wait = false`, whereas here it is `true`. This could mean `run_once` behaves differently for you and might not block in the first place, but I'm not sure.
> Fix shutdown signal handling in signer loop

- libs/gl-client/src/signer/mod.rs
Changes the derivation key for the master rune to be closer to what core-lightning is using.
> Change derivation key for master rune

- libs/gl-client/build.rs
It's basically the same PR as this one https://github.com/ElementsProject/lightning/pull/7015
But for Greenlight.
This allows easy pretty printing of responses received from the node.
> derive Serialize and Deserialize on grpc requests/responses

- libs/gl-client-py/src/credentials.rs
- libs/gl-client/src/credentials.rs
It was spewing out pages of raw binary data every time, which was
drowning my shell. Reducing the build of the credentials to its type,
and logging the raw credentials onces but at a lower severity sounds
like a good idea.
> client: Reduce noisy logging when creating TlsConfig from Credentials

- docker/gl-testing/Dockerfile
The `python-builder` is the first stage when building the Dockerfile.
It installs all python dependencies into a `venv`.
Installing dependencies is time-consuming and we want to cache this.
Therefore, we don't want to include the path-dependencies yet. If we
would add `gl-client` and `gl-testing` we would have to rebuild the
entire docker container every time we change a line in the code-base.
In the `python-builder` we first generate a list of dependencies using
`poetry export`. We filter out the path-dependencies of this list before
installing them.
However, the script to filter out the path-dependencies is broken. We
fail to filter out the path-dependencies. This modification fixes the
problem and ensures the pipeline runs again.
> CI: Do not install path-deps in `python-builder`

- libs/gl-testing/gltesting/utils.py
We were investigating the switch from signet to regtest in the test
environment, and I misidentified the solution as being an ordering, or
numbering issue in the `enum`. Turns out we were using an altogether
different enum in the first place, and that was causing the
issue. Nevertheless, lining these up the same way should prevent
accidental breakage if we end up using the numeric encoding somewhere.
Fixes #434
> rs: Reorder the network enum to match the `bitcoin` crate's enumeration

- libs/gl-client-py/glclient/__init__.py
- libs/gl-client/src/lib.rs
- libs/gl-client/src/runes.rs
- libs/gl-client/src/signer/mod.rs
- libs/gl-testing/tests/test_gl_node.py
- libs/gl-testing/tests/test_node.py
The goal of this PR is to provide a system that makes it easy and secure to construct runes with certain restrictions. We provide rule sets for common restrictions and combinations of those.
Example from a user perspective:
**A user wants to create and hand out a rune to a bookkeeping application (we all have to do taxes eventually):**
The application should not be allowed to move funds, neither off-chain nor on-chain but shall be able to read information from the node. A coarse rule set that is easy to understand (or at least human readable) and fulfills the task would be a **readonly** set that can be used to construct a rune that restricts the owner to read methods.
Example from an application perspective (pairing-protocol)
**A Podcast application uses greenlight without a distinct …
> Add Rule sets for Rune creation

- libs/gl-plugin/src/stager.rs
We have a couple of nodes that appear to have slow signers, let's
check that.
> plugin: Track signer <> node RTT for signer requests

- Makefile
- docker/gl-testing/Dockerfile
- libs/cln-version-manager/clnvm/cli.py
- libs/cln-version-manager/clnvm/cln_version_manager.py
- libs/cln-version-manager/clnvm/logging.conf
- libs/gl-testing/gltesting/scheduler.py
This is part of a bigger effort to make `gl-testing` a stand-alone package. One of the dependencies of `gl-testing` is a wide range of `lightningd`-executables.
The `cln_version_manager` can download these versions and provide them to `gl-testing`. I've introduced `cln_version_manger` before. This PR contains a couple of fixes and ensures `gl-testing` uses versions managed by `cln_version_manager`
- **cln_version_manager: Don't verify tag by default**
- **Rework Dockerfile to install binaries**
- **clnvm: Use non-zero exit code on error**
- **Add verbose option to cln_vm cli**
- **cln_version_manager: Use hash of patched version**
- **Use versions based on cln-version-manager**
- **Clean-up Makefile**
> use cln version manager

- libs/gl-client-py/.cargo/config.toml
Added the configuration targets needed to build with pyo3 on mac:
https://pyo3.rs/v0.14.2/building_and_distribution.html#macos
> build: added cargo config for pyo3 builds on mac.

- libs/gl-plugin/src/lib.rs
- libs/gl-plugin/src/messages.rs
We didnt implement parsing string correctly, leaving the extension unprased, causing the parser to err.
> plugin: Fix parsing of str or int amount_msat

- Makefile
It's failing to recognize `primitives_pb2.Amount` and `primitives_pb2.AmountOrAny`, likely because the types are runtime types and mypy doesn't get it.
> docs: Do not run mypy on the examples when publishing docs

- Cargo.toml
When pulling greenlight version 0.2.0 in Rust, I got the following error:
```
randy@HOME gl % cargo build
Compiling gl-client v0.2.0 (https://github.com/Blockstream/greenlight.git?rev=3a52042de220f1c6c3de171a6284c6d0177a5168#3a52042d)
error[E0412]: cannot find type `DelexpiredinvoiceRequest` in module `cln`
--> /Users/randy/.cargo/git/checkouts/greenlight-e41cf58dbd255ee0/3a52042/libs/gl-client/src/signer/model/mod.rs:41:28
|
41   |     DelExpiredInvoice(cln::DelexpiredinvoiceRequest),
|                            ^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `DelinvoiceRequest`
|
::: /Users/randy/Desktop/gldemo/gl/target/debug/build/cln-grpc-cdbfd96d73c34bc9/out/cln.rs:1800:1
|
1800 | pub struct DelinvoiceRequest {
| ---------------------------- similarly named …
```
> rs: Pin the cln-grpc dependency.

- .github/workflows/docs-action.yml
This sureley isnt ideal but it fixes the deployment for now. We need to enable the pyhon tests (mypi) in the future as well and we may want to switch to using the make target again. This would require to use `poetry run` consistently on the make targets.
> Fix docs workflow

- Cargo.lock
- Cargo.toml
- libs/gl-client-py/glclient/rpc.py
- libs/gl-client/src/signer/model/cln.rs
- libs/gl-client/src/signer/model/mod.rs
- libs/gl-client/src/signer/resolve.rs
- libs/gl-plugin/Cargo.toml
- libs/gl-plugin/src/lib.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-plugin/src/node/wrapper.rs
- libs/gl-plugin/src/pb.rs
We want to upgrade the `cln-*` crates to the latest version as `cln-rpc 0.1.9` adds the field `payment_metadata` to the `sendpay` rpc method. 
This enables a bunch of new methods on `gl-plugin` as well as notifications.
Some grpc methods are left unimplemented as they are experimental or do not make sense in the context of a greenlight node with a detached signer.
Please check if we should disable any other methods or implement some of the methods that I disabled for now.
> Upgrade cln-* crates

- Makefile
- docker/gl-testing/Dockerfile
We currently iterate quite fast on gl flavoured versions. With this commit we skip the check of the downloaded cln binary.
> Temporarily ignore hashes in clnvm

- Cargo.lock
- Cargo.toml
- libs/gl-client-py/glclient/rpc.py
- libs/gl-client/src/signer/model/cln.rs
- libs/gl-client/src/signer/model/mod.rs
- libs/gl-client/src/signer/resolve.rs
- libs/gl-plugin/Cargo.toml
- libs/gl-plugin/src/lib.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-plugin/src/node/wrapper.rs
- libs/gl-plugin/src/pb.rs
We postpone upgrading the cln-* crates to the next general upgrade of the signer and node version. Reverting this ensures that we can publish updates on the server side without droping support for older nodes too early.
Reverts Blockstream/greenlight#472
> Revert "Upgrade cln-* crates"

- libs/gl-client/src/signer/mod.rs
We want to capture policy signer rejections too, as they can help us identify problems for false negatives, and can be used to fine-tune policies, or act as a regression test suite should the rejection be a true positive.
Sadly we were not actually sending a rejection, due to a misplaces `?` that'd bubble up the error past the reporting spot. This PR addresses that by handling the response in a more fine-grained manner.
> signer: Capture signer rejections and report them

- .github/workflows/python.yml
- libs/gl-client/.resources/proto/glclient/greenlight.proto
- libs/gl-client/src/signer/mod.rs
- libs/gl-plugin/src/hsm.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-plugin/src/stager.rs
- libs/proto/glclient/greenlight.proto
When the signer rejects a request we had no indication as to what went
wrong until now. With this change we (a) send back the error as if it
were a normal response and then (b) print the error in the logs,
allowing us to collate the operations causing the rejection with the
rejection itself.
> signer: Pass policy rejections back to the node

- libs/gl-client-py/src/node.rs
- libs/gl-client-py/tests/plugins/trmp_htlc_hook.py
- libs/gl-client/src/node/mod.rs
This reverts commit adc05479b20a920d6206df117581fa0de6db146e until we know that it is really necessary to add the custom keep-alive.
> Revert trampoline keep-alive logic

- libs/gl-client/src/pairing/mod.rs
If used with tokio::sync::mpsc `SendError` requires PairingSessionData to implement std::fmt::Debug. Clippy is complining about this.
Resolves #500
> Derive "Debug" for PairingSessionData

- .gitattributes
- Makefile
- libs/gl-client/Makefile
- libs/gl-plugin/.resources/proto/glclient/greenlight.proto
- libs/gl-plugin/Makefile
- libs/gl-plugin/build.rs
- libs/gl-signerproxy/.resources/proto/glclient/greenlight.proto
- libs/gl-signerproxy/Makefile
- libs/gl-signerproxy/build.rs
- libs/gl-testing/Makefile
In order to publish the crates individually, we need to attach our resources to them. Currently this is mostly the proto files and the tls (nobody) certificates where needed.
This PR also adds some improvements to the Makefiles (also the root Makefile) for ease of use.
> Add .resources dir to all crates in workspace

- docs/mkdocs.yml
- docs/src/reference/node-domain.md
We have implemented the custom error codes, but havent documented
them publicly. This fixes that :-)
> docs: Document the Node Domain

- libs/gl-client-py/tests/test_plugin.py
- libs/gl-plugin/src/node/mod.rs
Trampoline pay returned the `payment_hash` hex encoded instead of raw bytes as other grpc calls do.
> Trampoline: Return payment_hash as bytes directly

- libs/gl-testing/pyproject.toml
The old version pattern was too restrictive to be useful.
> testing: Update cryptograhy to newer version

- libs/gl-client/src/signer/mod.rs
We have noticed that when changing a network while greenlight (using breez sdk) is running we no longer able to create an invoice.
Digging into this I have noticed the signer exists with these logs:
```
[2024-10-06 14:26:41.256 DEBUG tonic::codec::decode:204] decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: address not available", source: Some(hyper::Error(Body, Error { kind: Io(Kind(AddrNotAvailable)) })) }
[2024-10-06 14:26:41.256 DEBUG gl_client::signer:855] Got an error from the scheduler status: Unknown, message: "error reading a body from connection: address not available", details: [], metadata: MetadataMap { headers: {} }
[2024-10-06 14:26:41.256 ERROR gl_client::signer:807] Scheduler signer loop exited unexpectedly: Err(Scheduler …
```
> Ensure signer doesn't exit on connection change

- libs/gl-client/src/signer/mod.rs
We need to accept repeat signature requests and revocations for older
states because the signer state update and the CLN state update are
not atomic, i.e., the signer commits first, therefore ratchets up,
before CLN stores its state, meaning we could potentially replay some
prior state due to a preemption and restart inbetween. Relaxing these
two should address the majority of our desync issue.
> signer: Relax two rules to be warnings only

- libs/gl-plugin/src/tramp.rs
If the channel is unconfirmed it doesn't have a short_channel_id, but it does have a local alias. Include unconfirmed channels in the channel filter by initializing the `AwaitableChannel` with either the `short_channel_id` or the local alias. `AwaitableChannel` already works with the alias as well.
> enable trampoline for zero conf channels

- Cargo.lock
- libs/gl-cli/Cargo.toml
- libs/gl-cli/src/main.rs
- libs/gl-cli/src/scheduler.rs
- libs/gl-cli/src/signer.rs
- libs/gl-cli/src/util.rs
This PR addresses some of the improvements suggested in #515.
> Some CLI improvements

- docs/mkdocs.yml
- docs/src/reference/testserver.md
- libs/gl-testing/gltesting/certs.py
- libs/gl-testserver/gltestserver/__main__.py
- libs/gl-testserver/pyproject.toml
- libs/gl-testserver/tests/test_server.py
- pyproject.toml
This uses the `gl-testing` library, and builds a standalone server to
test against. We currently expose four interfaces:
- The scheduler interface as the main entrypoint to the service
- The GRPC-Web proxy to develop browser apps and extensions against
Greenlight.
- The `bitcoind` interface, so you can generate blocks and confirm
transactions without lengthy wait times
- The node's grpc interface directly to work against a single user's
node
All of these will listen to random ports initially. We write a small
file `metadata.json` which contains the URIs and ports for the first
three, while the node's URI can be retrieved from the scheduler, since
these are spawned on demand as users register.
Depends #536
> testserver: Standalone Greenlight testserver for non-python projects

- libs/gl-plugin/src/lsp.rs
- libs/gl-plugin/src/tlv.rs
- libs/gl-testing/tests/test_node.py
This PR makes all of the onion payload fields for the lsp clients `htlc_accepted` hook handler optional. We can not assume that all fields are set and we need to act to what we get. If the handler processes an onion payload that is missing essential fields it will stop executing and return the `continue` signal to core-lightning to pass the htlc to the next processor/handler in line.
Resolves #541
> Make onion fields optional on lsp client hook handler

- Makefile
- docker/gl-testserver/Dockerfile
- libs/gl-testing/pyproject.toml
- libs/gl-testserver/gltestserver/__main__.py
The `.envrc` file can make it simpler to configure your shell. In
addition we add `Makefile` targets.
> testserver: Add a couple of usability improvements

- libs/gl-client-py/pyproject.toml
- libs/gl-testing/gltesting/grpcweb.py
The generated files have a minimum dependency for the runtime of 1.67, so lets reflect that in the requirements.
> glclientpy: Upgrade protobuf dependencies

- libs/gl-client/src/lib.rs
As reported by the Breez team the cause for the `transport error` when
attempting a `trampoline_pay` appears to be that even short
interruptions in connectivity kill the TCP connections. The long 90s
timeout is causing `gl-client` to patiently sit there for the 90s,
ignoring all errors in the hope of getting the TCP connection
back. When it then attempts to re-establish the connection, any
pending call gets the dreaded `transport error`.
Reducing this to 5 seconds timeout and a 1s interval should minimize
the chances of issuing a command during the broken phase.
Suggested-by: Roei Erez <@roeierez>
Suggested-by: Jesse De Wit <@JssDWt>
Closes #428
> client: Tweak the keepalive interval and timeout

- libs/gl-plugin/src/tramp.rs
If a spendable channel balance exactly equals the amount, trampoline payment would create a zero value htlc. Never do that!
> tramp: never create zero value htlcs

- docker/gl-testing/Dockerfile
gltestserver requires GLIBC v2.34 or higher, but Ubuntu 20.04 ships with v2.31.
> docker: Updated Ubuntu from 20.04 to 22.04

- .github/workflows/python.yml
- .github/workflows/release.yml
> Artifact actions v3 will be closing down by January 30, 2025. You are receiving this email because you have GitHub Actions workflows using v3 of [actions/upload-artifact](https://app.github.media/e/er?s=88570519&lid=6648&elqTrackId=867ac6c9fa524bda9764f13bec8f8014&elq=cb3f66b75c2e4dffbd84b35f1097446c&elqaid=4286&elqat=1&elqak=8AF5D94B629B77D0B2E640E5D18BB16F1795B8B7563254EF101FA84EC79A1FE34BCA) or [actions/download-artifact](https://app.github.media/e/er?s=88570519&lid=6647&elqTrackId=bb54934dfd8c4c44b0e64ec2f2ba4824&elq=cb3f66b75c2e4dffbd84b35f1097446c&elqaid=4286&elqat=1&elqak=8AF57B355AADDDE608896B61A68B985ADA84B8B7563254EF101FA84EC79A1FE34BCA). After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible …
> github CI: actions/upload-artifact@v4 update

- libs/gl-plugin/src/tramp.rs
Remove the timeout on `waitsendpay` for trampoline. Payments may potentially take more than 2 minutes. The only reliable thing to do is wait until the payment parts come back. This could be aborted at any time by the greenlight node stopping or the client disconnecting. This brings `trampoline_pay` more in line with the behavior of `pay`, which will also wait indefinitely if a payment part is 'stuck' in the network.
> tramp: remove waitsendpay timeout

- libs/gl-plugin/src/tramp.rs
Ensure trampoline payments follow the following behavior:
- When a payment with the same payment hash had already completed, return a completed response.
- When a payment with the same payment hash is pending, return an error (ideally it should wait for payment parts to return)
- When a payment for the same payment hash is retried, bump the group id.
Fixes `Error code 201: There already is a payment with payment_hash=xxxxx, groupid=1, partid=0. Either change the partid, or wait for the payment to complete and start a new group.`
Also fixes potential accidental subsequent pays to the same payment hash.
> tramp: account for retried payments

- Makefile
- docker/gl-testserver/Dockerfile
- libs/gl-testserver/gltestserver/__main__.py
Just some followup fixes, and tweaks. It should be workable now.
> ts: Add Dockerfile and `make` targets

- libs/gl-client/src/signer/mod.rs
This should get the couple of nodes that are stuck on a large
commitment TX fee unstuck. We triple the feerate in order to not run
into the deadlock, and we make the policy failure a warning instead.
This is not a solution to #538, since it is just a one-time adjustment. Ideally we'd have an independent feerate oracle that VLS can query independently.
> signer: Increase the feerate for commitment TXs and warn on failure

- libs/gl-plugin/src/node/mod.rs
Adding log messages for success/failure of a trampoline payment.
Resolves #537
> Add additional log messages to trampoline payments

- .github/workflows/cln-version-manager-py.yml
- docker/gl-testing/Dockerfile
- Updated the `gl-testing` Dockerfile to use Poetry `1.8.2`, as Poetry `v2.x.x` installs the latest version of `pyln-grpc-proto` (`24.2.1`), which causes the `mypy glclient` check to fail. Poetry `1.8.2` installs `pyln-grpc-proto` version `0.1.3`, which works seamlessly with the CI.
- Added a check to ensure the group exists before adding it in the Docker.
- clnVersionManager: Locked Poetry version to `1.8.2` to allow for a coordinated upgrade in the future.
> ci: Fixes for failing workflows

- docs/pyproject.toml
- libs/gl-client/src/lsps/lsps2/schema.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-plugin/src/unix.rs
- libs/gl-testing/tests/test_grpc_web.py
- pyproject.toml
Just some some cleanups that resolve some warnings that `cargo` complaint about.
> Driveby cleanups

- docker/gl-testserver/Dockerfile
- Removed `RUN uv run clnvm get-all` since it fails with `No such file or directory (os error 2)` and is redundant, as the command runs later with `gltestserver run`.
- Set `GL_TESTING_IGNORE_HASH` to False to suppress the warning: "Checking the hash of remote versions is disabled, which is unsafe. Try to unset GL_TESTING_IGNORE_HASH."
> Remove explicit clnvm run

- Cargo.lock
- libs/gl-cli/Cargo.toml
- libs/gl-cli/src/bin/glcli.rs
- libs/gl-cli/src/lib.rs
In ordert to stick to the naming scheme that has established around greenlight crates which is `gl-<package>`, this PR changes the name of the crate to be published to crates.io.
When using the binary, the newly introduced hyphen might be a bit cumbersome so we keep the name of the binary `glcli`.
> Rename crate `glcli` -> `gl-cli`

- libs/cln-version-manager/.tasks.yml
CI was complaining about the usage of `--extra`, switch to `--dev` instead to include the `dev` dependency-group.
> Update `check` task

- .github/workflows/check-self.yml
- Taskfile.yml
- docker/gl-testing/Dockerfile
- libs/gl-client-py/.tasks.yml
- libs/gl-testing/.tasks.yml
- libs/gl-testing/tests/test_node.py
They got lost, re-adding them for a complete picture in CI
> Add `gl-testing` tests to CI

- libs/gl-plugin/src/tramp.rs
We had some incidents where a trampoline payment created `0msat` which lead to failed payments that actually did not fail. In order to avoid this we filter out channels that have a `spendable_msat` value of `0` or below the `minimum_htlc_out_msat`.
> Check for `spendable_msat` on trampoline pay

- docs/src/reference/webhooks.md
1. Enhanced clarity and structure for better readability.
2. Expanded explanations for event subscriptions, verification, and security best practices.
3. Provided step-by-step instructions for adding, managing, and rotating webhooks.
4. Ensured consistent formatting and correct Markdown syntax for seamless GitHub integration.
> Improved Webhooks Documentation for Greenlight

- libs/cln-version-manager/clnvm/cli.py
- libs/cln-version-manager/clnvm/cln_version_manager.py
- libs/cln-version-manager/clnvm/errors.py
- libs/cln-version-manager/pyproject.toml
The `clnvm` tool was way too quiet for my liking, so I added logging to `stderr` not to interfere with tooling that may already rely on the tool printing the paths of versions to `stdout`.
I then also added the new version to deploy in `prod`.
> clnvm: Add v24.11gl1 and make it a bit more verbose

- libs/gl-plugin/src/tramp.rs
The way we allocated channels for a trampoline payment could lead to a case where we could get stuck selecting channels for a payment when the rest amount was lower than the lower bound of the channel.
This PR introduces a new selection logic that tries to be greedy first but will split payments more carefully if it is actually needded.
Reviewers: Please check carefully and let me know if you need more tests.
> Trampoline: Improve channel selection logic

- docker/gl-testing/Dockerfile
Enable multi-architecture support to ensure proper protoc downloads based on the build environment.
This fixes issues on Apple Silicon (ARM64) where the x86_64 binary was previously being downloaded,
leading to the missing ld-linux-x86-64.so.2 error.
* Use the same protocol buffer compiler version across architectures
* Ensure Docker build success on Apple Silicon
> gl-testing: enable multi-arch protoc download for Apple Silicon

- Makefile
- docker/gl-testing/Dockerfile
- docs/src/tutorials/testing.md
Add and refine arm64 support by introducing multi-arch Docker builds for both Bitcoin Core and Cloudflare’s CFSSL binaries, switching `uv sync --extra dev` to `uv sync --group dev`, and updating documentation to consistently use `uv run`. This improves cross-platform compatibility and streamlines the development workflow.
> Refine ARM64 multi-arch Docker builds and dev workflow

- libs/gl-client/src/node/generic.rs
- libs/gl-client/src/node/mod.rs
https://github.com/Blockstream/greenlight/issues/597 
Lift the maximum decoding message size from 4MB to 32MB by default.
Prevent large gRPC responses from failing.
Make it configurable via the Node builder.
We trust the server logic, so increasing the default is safe.
> glclient: lift default decoding size

- docker/gl-testserver/Dockerfile
Issue: [#563](https://github.com/Blockstream/greenlight/issues/563)
Reduces the image size for the gl-testserver by switching to a multi-stage Dockerfile build.  
The previous image was around 9 GiB, causing long build/fetch times and taking up unnecessary space in development environments. With this change, the image footprint has been reduced to approximately 500MB.
```sh
docker images
REPOSITORY                      TAG       IMAGE ID       CREATED             SIZE
gltestserver                    latest    9fe837b67bad   About an hour ago   525MB
```
Also enable multi-architecture support.
> testserver: slim testserver image

- libs/cln-version-manager/clnvm/cln_version_manager.py
> chore: Update the CLN v24.11gl1 hash

- Cargo.lock
- Cargo.toml
- Makefile
- Taskfile.yml
- docker/gl-testing/Dockerfile
- libs/gl-client-py/.tasks.yml
- libs/gl-client-py/glclient/__init__.py
- libs/gl-client-py/pyproject.toml
- libs/gl-client/src/lnurl/pay/mod.rs
- libs/gl-client/src/persist.rs
- libs/gl-client/src/signer/mod.rs
- libs/gl-client/src/signer/resolve.rs
- libs/gl-plugin/src/tramp.rs
- libs/gl-testing/gltesting/grpcweb.py
- libs/gl-testing/gltesting/node.py
- libs/gl-testing/gltesting/scheduler.py
- libs/gl-testing/gltesting/utils.py
- libs/gl-testing/pyproject.toml
- libs/gl-testing/tests/test_grpc_web.py
- libs/gl-testing/tests/test_node.py
This PR adds support for CLN v24.11. It'll trigger an upgrade on the
node as soon as it connects the first time, and will act as its signer
from thereon.
We're keeping it a draft, while we verify the core functionality, and
will merge as soon as it is deemed stable. Feel free to use this
signer version, however be aware that there is currently no way to
downgrade once upgraded, so use test nodes.
> signer: Add CLN v24.11 to supported versions

- Cargo.lock
- Cargo.toml
- libs/gl-client-py/tests/test_plugin.py
- libs/gl-plugin/Cargo.toml
- libs/gl-plugin/src/awaitables.rs
- libs/gl-plugin/src/lib.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-plugin/src/tramp.rs
- libs/gl-util/Cargo.toml
- libs/gl-util/src/error.rs
- libs/gl-util/src/lib.rs
This PR introduces a comprehensive error handling framework for trampoline payments, replacing generic `anyhow::Error` usage with strongly-typed, domain-specific errors. The error handling provides better error categorization, improved diagnostics, and seamless gRPC integration. It also adds rich error context with hints for developers and users while surviving serialization into gRPC statuses for usage across service boundaries.
> Add Domain Specific Error Handling for Trampoline Payments

- libs/gl-client-py/glclient/__init__.py
retry_for argument in pay is optional in core-lightning let's keep it that way also during tests.
We were trying to intercept pay requests and redirect them to xpay and renepay but with retry_for=0 renepay would inmediately fail during testing sessions. We were not expecting that the value of retry_for was being set to 0 instead
of being forwarded as an optional argument.
> gl-client-py: make retry_for optional

- examples/rust/snippets/getting_started.rs
- libs/gl-client/src/signer/mod.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-signerproxy/src/hsmproxy.rs
We were always pinning the TLS SNI domain to `localhost`. That worked
while we were using IP-based URIs to connect to the node. It does no
longer work with the node domain proxy which is behind a GCP anycast
load balancer, which drops connections claiming to be for `localhost`.
> signer: Allow the signer to go through the node domain
