Blockstream/greenlight

- docs/src/getting-started/schedule.md
Adds missing brackets in constructor, fixes typo and calls the right function name.
> Fixes typos and updates method reference

- docs/mkdocs.yml
- docs/src/about/faq.md
- docs/src/getting-started/installation.md
- libs/gl-client-py/pyproject.toml
- tools/glcli/README.md
Collecting some fixes.
Fixes #171
> docs: Some minor fixes

- libs/gl-client-py/pyproject.toml
- libs/gl-testing/Dockerfile
Adds a missing dependency and updates cargo to get sparse repo updates.
Reported-by: @Jossec101
Fixes #191
> Cargo update and missing dependency

- .github/workflows/javascript.yml
- .gitignore
- libs/gl-client-js/Cargo.toml
- libs/gl-client-js/package.json
- libs/gl-client-py/Cargo.toml
- libs/gl-client-py/pyproject.toml
- libs/gl-client/Cargo.toml
This addresses #179 among other things
> js: Fix architecture mismatch between Rust target and Node process architecture

- libs/gl-client/src/signer/mod.rs
Expose the `sign_message` function on the signer, in order to allow clients to sign messages themselves. `sign_message` now also returns the recovery id, in order to provide full capabilities of encoding a lightning signed message to external people.
> signer: expose sign_message with recovery id

- libs/gl-client/src/signer/mod.rs
Investigating an issue when calling `maybe_upgrade` and it turns out we were just overwriting the message with a generic one that wasn't telling us much.
> signer: Return a wrapped error, don't overwrite it

- libs/gl-client/src/signer/mod.rs
> Skip the request len on type check

- libs/gl-client/src/signer/mod.rs
We can leave out the bytes buffer in `process_request` altogether since we utilize the vls protocol message constructor `from_vec` that just takes the raw message.
> Read from raw message

- Makefile
- libs/Cargo.lock
- libs/gl-client-py/glclient/__init__.py
- libs/gl-client/Cargo.toml
- libs/gl-client/src/persist.rs
- libs/gl-client/src/signer/mod.rs
- libs/gl-testing/Dockerfile
- libs/gl-testing/gltesting/fixtures.py
- libs/gl-testing/gltesting/node.py
- libs/gl-testing/gltesting/utils.py
> signer: Add CLN v23.08 support

- libs/gl-client/src/lsps/error.rs
- libs/gl-client/src/lsps/json_rpc.rs
- libs/gl-client/src/lsps/json_rpc_erased.rs
- libs/gl-client/src/lsps/message.rs
- libs/gl-client/src/lsps/transport.rs
Applied clippy hints to make code more idiomatic.
The changes in this commit are mostly cosmetic.
I've only included the lsps to avoid generating merge-conflicts with the work of others.
> Clippy improvements

- tools/glcli/glcli/cli.py
> Added sigint signal handler to glcli's hsmd command.

- libs/gl-client/src/signer/model/cln.rs
- libs/gl-client/src/signer/model/mod.rs
- libs/gl-client/src/signer/resolve.rs
Just some drive-by fixes
Fixes #280
> Minor fixups

- libs/gl-client-py/glclient/__init__.py
- tools/glcli/glcli/cli.py
Fixes `connect` command.
Adds `decode` command.
Adds `decodepay` command.
> Some CLI additions

- Cargo.lock
- libs/gl-client/Cargo.toml
- libs/gl-client/src/node/mod.rs
- libs/gl-client/src/scheduler.rs
- libs/gl-client/src/signer/mod.rs
Futhark was already used, it is called `runeauth` now.
> Upgrade futhark to authrunes crate on crates.io

- libs/gl-client/src/signer/mod.rs
If the signer loop (`run_forever`) is called when there is no network available, the loop exits because `scheduler.maybe_upgrade` fails.
We've tried handling this outside the signer loop, by re-starting the loop when connection-related errors are thrown (https://github.com/breez/breez-sdk/pull/691). But it's rather unwieldy and verbose.
Handling it inside the signer loop seems like a better choice, which is the focus of this PR.
> Signer loop: retry upgrade on connection error

- .github/workflows/docs-action.yml
- docs/mkdocs.yml
It seems to be missing permissions.
> Fix the page builder workflow

- Cargo.lock
- Cargo.toml
- libs/gl-plugin/src/lib.rs
- libs/gl-plugin/src/lsp.rs
- libs/gl-plugin/src/node/mod.rs
- libs/gl-plugin/src/node/wrapper.rs
This PR simply bumps the 3 dependencies to the latest v0.1.8.
> Bump cln-grpc, cln-rpc and cln-plugin to 0.1.8

- libs/gl-client-py/src/scheduler.rs
- libs/gl-client/src/scheduler.rs
Removed the protobuf models from the outgoing webhook method signatures in Rust.
> Simplified outgoing webhook methods.

- libs/gl-plugin/src/lib.rs
- libs/gl-plugin/src/node/mod.rs
- **plugin: Change datastore mode on peer_connected**
- **plugin: Enhance logging of reconnect_peers**
> Enable overriding of peer addresses in datastore

- .github/workflows/docs-action.yml
This PR adds `mypy` to the venv that is used by the CI.
> Fix docs CI pipeline

- docs/src/getting-started/installation.md
Recommend using a tagged installation.
> docs: Do not recommend installation from git

- libs/cln-version-manager/clnvm/cln_version_manager.py
Updates the hash for v24.02gl1
> Update clnvm hash for v24.02gl1

- Cargo.toml
This is mainly to pull in the regression fix for #476
Closes #476
> signer: Upgrade the signer to VLS 0.11.1

- libs/gl-plugin/src/node/mod.rs
The client is disconnecting right away, then reconnecting, and retrying the same request over and over again. That's not correct, and we should stay connected, but not return the signer response if we could not persist the associated signer state. This is equivalent to before, the signer state version collision still happens, but the client doesn't enter the busy loop.
> plugin: Do not pass signer store persistence error to the client

- libs/gl-client/src/lnurl/withdraw/mod.rs
> rs: Silence a lint about tests rather than test

- libs/gl-client/.resources/proto/glclient/greenlight.proto
- libs/gl-client/src/lsps/lsps2/schema.rs
- libs/gl-client/src/signer/auth.rs
- libs/gl-client/src/signer/model/greenlight.rs
- libs/gl-client/src/signer/model/mod.rs
- libs/gl-client/src/signer/resolve.rs
- libs/proto/glclient/greenlight.proto
We were using these in the very beginning, removing them now in favor of cln-grpc-proto.
> proto: Remove deprecated proto parts

- .github/workflows/docs-action.yml
Fixes the path to the rust examples in the github action.
> Fix path to rust examples in github action

- .github/workflows/cln-version-manager-py.yml
- .github/workflows/python.yml
- libs/gl-client/src/signer/mod.rs
> Upgrade CI images from ubuntu:20.04 to ubuntu:24.04
